<PredictButton@PredictButton>:
    text: "predict stock"

<BoxLayout>:
    orientation: "vertical"

    Label:
        text: "StockPredict"
        font_name: "Impact"
        font_size: 42
        size_hint_y: .2

    GridLayout:
        columns: 3
        rows: 1
        size: root.x, root.y

        PredictButton:
            text: "Predict Stock"

        Button:
            text: "Headline Impact"

        Button:
            text: "Word Impact"