<NutButton@Button>:
    text: "NUT"
    color: 0, 0, 0, 1
    font_size: 32
    font_name: "Impact"
    background_color: 0, 0, 1, 1

<ShitButton@Button>:
    text: "SHIT"
    color: 1, 0, 1, .5
    font_size: 24
    font_name: "Impact"
    background_color: 1, 0, 0, 1

<GridLayout>:
    cols: 2
    rows: 2
    spacing: 10
    padding: 10

    NutButton:
        pos_hint: {"right": 1, "y": 0}

    ShitButton:
        pos_hint: {""}
